[build]
  command = "/Applications/RStudio.app/Contents/Resources/app/quarto/bin/quarto render"
  publish = "_site"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  QUARTO_VERSION = "1.0.0"
